vich_uploader:
    db_driver: orm

    mappings:
        challenge:
            uri_prefix: /images/challenge
            upload_destination: '%kernel.project_dir%/public/images/challenge'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
